// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/kimvlry/avito-internship-assignment/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"
)

// UserRepository is an autogenerated mock type for the UserRepository type
type UserRepository struct {
	mock.Mock
}

// CheckUsersAvailableForTeam provides a mock function with given fields: ctx, userIDs, teamName
func (_m *UserRepository) CheckUsersAvailableForTeam(ctx context.Context, userIDs []string, teamName string) error {
	ret := _m.Called(ctx, userIDs, teamName)

	if len(ret) == 0 {
		panic("no return value specified for CheckUsersAvailableForTeam")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []string, string) error); ok {
		r0 = rf(ctx, userIDs, teamName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Create provides a mock function with given fields: ctx, user
func (_m *UserRepository) Create(ctx context.Context, user *entity.User) error {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.User) error); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Exists provides a mock function with given fields: ctx, id
func (_m *UserRepository) Exists(ctx context.Context, id string) (bool, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *UserRepository) GetByID(ctx context.Context, id string) (*entity.User, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entity.User, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entity.User); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByTeam provides a mock function with given fields: ctx, teamName
func (_m *UserRepository) GetByTeam(ctx context.Context, teamName string) ([]entity.User, error) {
	ret := _m.Called(ctx, teamName)

	if len(ret) == 0 {
		panic("no return value specified for GetByTeam")
	}

	var r0 []entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]entity.User, error)); ok {
		return rf(ctx, teamName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []entity.User); ok {
		r0 = rf(ctx, teamName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, teamName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRandomActiveTeamUsers provides a mock function with given fields: ctx, teamName, excludeUserIDs, maxCount
func (_m *UserRepository) GetRandomActiveTeamUsers(ctx context.Context, teamName string, excludeUserIDs []string, maxCount int) ([]entity.User, error) {
	ret := _m.Called(ctx, teamName, excludeUserIDs, maxCount)

	if len(ret) == 0 {
		panic("no return value specified for GetRandomActiveTeamUsers")
	}

	var r0 []entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []string, int) ([]entity.User, error)); ok {
		return rf(ctx, teamName, excludeUserIDs, maxCount)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []string, int) []entity.User); ok {
		r0 = rf(ctx, teamName, excludeUserIDs, maxCount)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []string, int) error); ok {
		r1 = rf(ctx, teamName, excludeUserIDs, maxCount)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetIsActive provides a mock function with given fields: ctx, id, isActive
func (_m *UserRepository) SetIsActive(ctx context.Context, id string, isActive bool) (*entity.User, error) {
	ret := _m.Called(ctx, id, isActive)

	if len(ret) == 0 {
		panic("no return value specified for SetIsActive")
	}

	var r0 *entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, bool) (*entity.User, error)); ok {
		return rf(ctx, id, isActive)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, bool) *entity.User); ok {
		r0 = rf(ctx, id, isActive)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, bool) error); ok {
		r1 = rf(ctx, id, isActive)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, user
func (_m *UserRepository) Update(ctx context.Context, user *entity.User) error {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.User) error); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewUserRepository creates a new instance of UserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserRepository {
	mock := &UserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
